DROP TABLE IF EXISTS os_address.nspl;

CREATE TABLE os_address.nspl
(
    pcd character varying(7),
    pcd2 character varying(8),
    pcds character varying(8),
    dointr character varying(6),
    doterm character varying(6),
    usertype smallint,
    oseast1m character varying(20),
    osnrth1m character varying(20),
    osgrdind smallint,
    oa11 character varying(9),
    cty character varying(9),
    ced character varying(9),
    laua character varying(9),
    ward character varying(9),
    hlthau character varying(9),
    nhser character varying(9),
    ctry character varying(9),
    rgn character varying(9),
    pcon character varying(9),
    eer character varying(9),
    teclec character varying(9),
    ttwa character varying(9),
    pct character varying(9),
    nuts character varying(9),
    park character varying(9),
    lsoa11 character varying(9),
    msoa11 character varying(9),
    wz11 character varying(9),
    ccg character varying(9),
    bua11 character varying(9),
    buasd11 character varying(9),
    ru11ind character varying(9),
    oac11 character varying(9),
    lat double precision,
    "long" double precision,
    lep1 character varying(9),
    lep2 character varying(9),
    pfa character varying(9),
    imd integer,
    calncv character varying(9),
    stp character varying(9)
)
