DROP TABLE IF EXISTS os_address.nspl;

CREATE TABLE os_address.nspl
(
    pcd character varying(7),
    pcd2 character varying(8),
    pcds character varying(8),
    dointr character varying(6),
    doterm character varying(6),
    usertype smallint,
    oseast1m character varying(20),
    osnrth1m character varying(20),
    osgrdind smallint,
    oa21 character varying(9),
    cty character varying(9),
    ced character varying(9),
    laua character varying(9),
    ward character varying(9),    
	nhser character varying(9),
    ctry character varying(9),
    rgn character varying(9),
    pcon character varying(9),
    ttwa character varying(9),
	itl character varying(9),
	npark character varying(9),
	lsoa21 character varying(9),
	msoa21 character varying(9),
    wz11 character varying(9),	
	sicbl character varying(9),
	bua22 character varying(9),
	ru11ind character varying(9),
	oac11 character varying(9),
    lat double precision,
    "long" double precision,	
    lep1 character varying(9),
    lep2 character varying(9),
    pfa character varying(9),
    imd integer,	
	icb character varying(9)
)
